import { ScenarioPreset } from './types';

export const SCENARIO_PRESETS: ScenarioPreset[] = [
  {
    id: 'clean-passport',
    title: 'Valid Indian Passport (Clear Pass)',
    badge: 'CLEAR (96% Match)',
    description: 'Authentic Indian passport. Valid ICAO 9303 checksums, uniform ELA compression, valid 1:1 facial biometric match.',
    data: {
      id: 'DOC-2026-001',
      timestamp: '2026-09-12 19:30:15 IST',
      tokenNumber: 'SSB-2026-89412',
      documentType: 'PASSPORT',
      extractedFields: {
        fullName: 'RAHUL VERMA',
        documentNumber: 'Z8941209',
        nationality: 'IND',
        dateOfBirth: '14/08/1996',
        expiryDate: '13/08/2034',
        gender: 'M',
        issuingCountry: 'IND',
        mrzLine1: 'P<INDFVERMA<<RAHUL<<<<<<<<<<<<<<<<<<<<<<<<<<',
        mrzLine2: 'Z8941209<2IND9608144M3408138<<<<<<<<<<<<<<<0',
      },
      icaoDetails: {
        documentNumberValid: true,
        dobValid: true,
        expiryValid: true,
        compositeValid: true,
        rawAlgorithm: 'ICAO Doc 9303 Part 3/7 (Modulus 10, 7-3-1 weights)',
        overallIcaoCompliant: true,
        notes: ['All check-digits match official ICAO standards.', 'VIZ extracted names exactly match MRZ encoding.'],
      },
      tamperDetails: {
        photoReplacementDetected: false,
        photoSeamConfidence: 0.04,
        textManipulationDetected: false,
        fontInconsistencyScore: 0.03,
        stampForgeryDetected: false,
        stampCircularityAnomaly: 0.02,
        elaAnomalyScore: 0.05,
        metadataTampered: false,
        flaggedRegions: [],
      },
      biometricDetails: {
        faceMatched: true,
        similarityScore: 96.4,
        livenessVerified: true,
        livenessConfidence: 98.2,
        faceDetectedInDocument: true,
        liveFeedAvailable: true,
      },
      watchlistHit: false,
      riskScore: 12,
      riskLevel: 'LOW',
      verdict: 'CLEAR',
      executiveSummary: 'Document is authentic. ICAO Doc 9303 checksums verified. Live facial match 96.4%. Cleared for transit.',
      documentImageUrl: '/samples/passport_clean.svg',
      documentFaceUrl: '/samples/face_clean_doc.svg',
      liveTravelerPhotoUrl: '/samples/face_clean_live.svg',
    },
  },
  {
    id: 'tampered-expiry',
    title: 'Text-Forged Expiry Date (High Risk)',
    badge: 'FORGERY (Checksum Fail)',
    description: 'Document date of expiry was digitally edited from 2024 to 2034. ICAO checksum mismatch & ELA pixel disturbance flagged.',
    data: {
      id: 'DOC-2026-002',
      timestamp: '2026-09-12 19:32:40 IST',
      tokenNumber: 'SSB-2026-89413',
      documentType: 'PASSPORT',
      extractedFields: {
        fullName: 'SAMEER KHAN',
        documentNumber: 'K4519283',
        nationality: 'IND',
        dateOfBirth: '05/11/1991',
        expiryDate: '04/11/2034', // Forged from 2024
        gender: 'M',
        issuingCountry: 'IND',
        mrzLine1: 'P<INDKHAN<<SAMEER<<<<<<<<<<<<<<<<<<<<<<<<<<<',
        mrzLine2: 'K4519283<7IND9111058M3411048<<<<<<<<<<<<<<<4', // Expected check digit differs
      },
      icaoDetails: {
        documentNumberValid: true,
        dobValid: true,
        expiryValid: false,
        compositeValid: false,
        rawAlgorithm: 'ICAO Doc 9303 Part 3/7 (Modulus 10, 7-3-1 weights)',
        overallIcaoCompliant: false,
        notes: [
          'CRITICAL: Expiry date check-digit failed. VIZ shows 2034 but check digit calculation reports invalid residue.',
          'Composite MRZ checksum mismatch detected: document text has been artificially altered.',
        ],
      },
      tamperDetails: {
        photoReplacementDetected: false,
        photoSeamConfidence: 0.08,
        textManipulationDetected: true,
        fontInconsistencyScore: 0.84,
        stampForgeryDetected: false,
        stampCircularityAnomaly: 0.05,
        elaAnomalyScore: 0.89,
        metadataTampered: true,
        detectedEditingSoftware: 'Adobe Photoshop 24.1 (Windows)',
        flaggedRegions: [
          {
            field: 'Expiry Date',
            description: 'Digital pixel splicing and compression artifact boundary detected around expiry date numbers.',
            severity: 'HIGH',
            box: { x: 37, y: 38, width: 14, height: 4 },
          },
          {
            field: 'MRZ Line 2 - Pos 21-27',
            description: 'Font kerning mismatch and altered check-digit baseline alignment.',
            severity: 'HIGH',
            box: { x: 19, y: 45, width: 62, height: 4 },
          },
        ],
      },
      biometricDetails: {
        faceMatched: true,
        similarityScore: 91.2,
        livenessVerified: true,
        livenessConfidence: 94.0,
        faceDetectedInDocument: true,
        liveFeedAvailable: true,
      },
      watchlistHit: false,
      riskScore: 88,
      riskLevel: 'HIGH',
      verdict: 'DETAIN',
      executiveSummary: 'ALERT: Text forgery detected in Expiration Date. ICAO checksum validation failed. ELA confirms localized re-compression tampering.',
      documentImageUrl: '/samples/passport_tampered_expiry.svg',
      documentFaceUrl: '/samples/face_clean_doc.svg',
      liveTravelerPhotoUrl: '/samples/face_clean_doc.svg',
    },
  },
  {
    id: 'photo-replaced',
    title: 'Photo-Replaced Impersonation (High Risk)',
    badge: 'IMPERSONATION (Face Mismatch)',
    description: 'Imposter pasted a new photo over a stolen passport. Boundary cut-and-paste seam detected and 1:1 facial biometric match fails.',
    data: {
      id: 'DOC-2026-003',
      timestamp: '2026-09-12 19:35:10 IST',
      tokenNumber: 'SSB-2026-89414',
      documentType: 'PASSPORT',
      extractedFields: {
        fullName: 'AMIT ROY',
        documentNumber: 'T7819034',
        nationality: 'IND',
        dateOfBirth: '22/03/1988',
        expiryDate: '21/03/2028',
        gender: 'M',
        issuingCountry: 'IND',
        mrzLine1: 'P<INDROY<<AMIT<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<',
        mrzLine2: 'T7819034<5IND8803221M2803213<<<<<<<<<<<<<<<1',
      },
      icaoDetails: {
        documentNumberValid: true,
        dobValid: true,
        expiryValid: true,
        compositeValid: true,
        rawAlgorithm: 'ICAO Doc 9303 Part 3/7 (Modulus 10, 7-3-1 weights)',
        overallIcaoCompliant: true,
        notes: ['Raw text and MRZ checksums passed.'],
      },
      tamperDetails: {
        photoReplacementDetected: true,
        photoSeamConfidence: 0.94,
        textManipulationDetected: false,
        fontInconsistencyScore: 0.06,
        stampForgeryDetected: false,
        stampCircularityAnomaly: 0.04,
        elaAnomalyScore: 0.92,
        metadataTampered: false,
        flaggedRegions: [
          {
            field: 'Photo Box Perimeter',
            description: 'Physical cut-and-paste seam and irregular shadow gradient detected around passport portrait border.',
            severity: 'HIGH',
            box: { x: 18, y: 30, width: 18, height: 16 },
          },
        ],
      },
      biometricDetails: {
        faceMatched: false,
        similarityScore: 34.2, // Failed
        livenessVerified: true,
        livenessConfidence: 96.5,
        faceDetectedInDocument: true,
        liveFeedAvailable: true,
      },
      watchlistHit: true,
      watchlistDetails: 'Impersonation Suspect: Stolen Passport reported in Interpol Stolen and Lost Travel Documents (SLTD) database.',
      riskScore: 96,
      riskLevel: 'HIGH',
      verdict: 'DETAIN',
      executiveSummary: 'CRITICAL ALERT: Photo replacement detected on document. Facial similarity score 34.2% (Failed threshold 68%). Interpol SLTD watchlist hit.',
      documentImageUrl: '/samples/passport_photo_replaced.svg',
      documentFaceUrl: '/samples/face_imposter_doc.svg',
      liveTravelerPhotoUrl: '/samples/face_clean_live.svg',
    },
  },
  {
    id: 'forged-stamp',
    title: 'Irregular Visa Entry Stamp (Review Required)',
    badge: 'REVIEW (Stamp Anomaly)',
    description: 'Transit visa with suspicious border crossing stamp. Non-standard ink chromaticity and circular distortion flagged for secondary inspection.',
    data: {
      id: 'DOC-2026-004',
      timestamp: '2026-09-12 19:37:00 IST',
      tokenNumber: 'SSB-2026-89415',
      documentType: 'VISA',
      extractedFields: {
        fullName: 'TENZIN DORJI',
        documentNumber: 'V9028114',
        nationality: 'NPL',
        dateOfBirth: '12/07/1993',
        expiryDate: '11/07/2027',
        gender: 'M',
        issuingCountry: 'NPL',
        visaType: 'BORDER TRANSIT PERMIT',
        stayDurationDays: 30,
        entryValidity: 'MULTIPLE',
      },
      icaoDetails: {
        documentNumberValid: true,
        dobValid: true,
        expiryValid: true,
        compositeValid: true,
        rawAlgorithm: 'ICAO Doc 9303 Part 7',
        overallIcaoCompliant: true,
        notes: ['MRV-B Format valid.'],
      },
      tamperDetails: {
        photoReplacementDetected: false,
        photoSeamConfidence: 0.12,
        textManipulationDetected: false,
        fontInconsistencyScore: 0.15,
        stampForgeryDetected: true,
        stampCircularityAnomaly: 0.68,
        elaAnomalyScore: 0.44,
        metadataTampered: false,
        flaggedRegions: [
          {
            field: 'Immigration Entry Stamp',
            description: 'Non-standard stamp ink color spectrum (RGB hue variance > 30%) and irregular circular contour curvature.',
            severity: 'MEDIUM',
            box: { x: 74, y: 31, width: 8, height: 7 },
          },
        ],
      },
      biometricDetails: {
        faceMatched: true,
        similarityScore: 89.5,
        livenessVerified: true,
        livenessConfidence: 95.0,
        faceDetectedInDocument: true,
        liveFeedAvailable: true,
      },
      watchlistHit: false,
      riskScore: 54,
      riskLevel: 'MEDIUM',
      verdict: 'SECONDARY_INSPECTION',
      executiveSummary: 'FLAGGED: Suspicious border immigration stamp on Visa. Circular geometry distortion and non-standard ink spectrum. Officer secondary review advised.',
      documentImageUrl: '/samples/passport_clean.svg',
      documentFaceUrl: '/samples/face_tenzin.svg',
      liveTravelerPhotoUrl: '/samples/face_tenzin.svg',
      hasVisa: true,
      visaImageUrl: '/samples/visa_forged_stamp.svg',
      visaDetails: {
        visaNumber: 'NPL-V-9028114',
        passportNumberLinked: 'V9028114',
        visaType: 'BORDER TRANSIT PERMIT',
        stayDurationDays: 30,
        entryValidity: 'MULTIPLE',
        validFrom: '12/07/2026',
        validUntil: '11/07/2027',
        issuingPost: 'CONSULAR POST BIRGUNJ',
        passportMatched: true,
        nameMatched: true,
        nationalityMatched: true,
        validityAligned: true,
        overallCrossCheckPassed: true,
        crossCheckNotes: [
          'Traveler credentials match between Passport and Visa Permit.',
          'WARNING: Visa endorsement stamp displays physical distortion / circularity anomaly.'
        ]
      }
    },
  },
];
